Clean up du nom d'instance

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,5 +1,21 @@
 #!/bin/bash
-cd ./src/express_webapp
-npm start > /dev/null 2>/dev/null &
-cd ../../
-echo "Service démarré sur le port 3000 : http://localhost:3000"
+
+# Change directory to the application directory
+cd ./src/express_webapp || exit
+
+# Start the Node.js application in the background
+npm start > /dev/null 2>&1 &
+pid=$!
+
+# Check if the startup was successful
+if [ $? -eq 0 ]; then
+  echo "Service started on port 3000: http://localhost:3000"
+else
+  echo "Error starting the service."
+fi
+
+# Change back to the previous directory
+cd - || exit
+
+# Optional: Wait for a few seconds before displaying the message
+sleep 2
diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+# Terminate all processes named 'node'
 pkill -9 'node'
+
+# Terminate all processes related to "npm start"
 pkill -9 "npm start"
-echo "Service arrêté"
+
+# Check if any processes were terminated
+if [ $? -eq 0 ]; then
+  echo "Service stopped"
+else
+  echo "Error stopping the service"
+fi
